name: flutter_mobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Environment variables
  flutter_dotenv: ^5.2.1
  path_provider: ^2.0.15

  # Carousel slider
  carousel_slider: ^5.0.0

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_messaging: ^15.2.5
  firebase_analytics: ^11.4.5

  # Local notifications
  flutter_local_notifications: ^19.2.0

  # Google Sign In
  google_sign_in: ^6.3.0

  # Google Maps
  google_maps_flutter: ^2.12.1

  # Location
  location: ^8.0.0
  geolocator: ^14.0.0

  # State management
  flutter_bloc: ^9.0.0

  # Dart object comparison
  equatable: ^2.0.7

  # Service locator
  get_it: ^8.0.3

  # Date formating i lokalizacija
  intl: ^0.19.0

  # Local (sqlite) Database
  floor: ^1.5.0

  # API requests
  retrofit: ^4.4.2

  # Hooks (kao u reactu)
  flutter_hooks: ^0.21.2

  # Cached image
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  bloc: ^9.0.0

  # SVG
  flutter_svg: ^2.0.15

  # Http
  http: ^1.4.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15

  flutter_test:
    sdk: flutter

dependency_overrides:
  web: ^0.5.1

  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.9
  floor_generator: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/music/
    - assets/images/food/
    - assets/images/culture/
    - assets/images/attraction/
    - assets/images/hobby/
    - assets/images/search/
    - .env

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300

  generate: true